name: Fetch stock data

on:
  schedule:
    - cron: "*/15 3-10 * * 1-5"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install tradingview-datafeed
        pip install pandas numpy pyarrow requests openpyxl scipy matplotlib

    - name: Run fetch script
      run: python "All Data Fetch.py"

    - name: Commit changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add -A                   # <---- key change
        git commit -m "Auto update data" || echo "No changes"
        git push
      continue-on-error: true
