name: Fetch stock data

on:
  schedule:
    - cron: "*/15 3-10 * * 1-5"   # 9:00–16:00 IST, Mon–Fri
  workflow_dispatch:              # allow manual run

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install pandas tvDatafeed pyarrow

    - name: Run fetch script
      run: python fetch_data.py

    - name: Commit changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Auto update data"
        git push
      continue-on-error: true
